version: "3.9"

services:
  node:
    build: .
    container_name: jobfit-ai_api
    command: >
      sh -c "npm install &&
             npm run start:dev"
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  db:
    container_name: db
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}